# Site settings
name: EmberCLI
description: A command line utility for creating ambitious web apps
baseurl: ''
url: http://ember-cli.com
markdown: kramdown

# Build
sass:
  style: :compressed

gems:
  - jekyll-feed
  - github-pages
